### ISSUE TITLE
Illegal base64 data

### ISSUE THREAD

**Issue by Thanzex** [dim13/otpauth#12]
Hi there!
I just stumbled upon this project, i'm exporting my Google Authenticator data but I cannot make this package work.
According to what I read and what this app expects, the link data should be B64 encoded, however, mine contains many `/` and `+`, 
this is my anonimized link.
`otpauth-migration://offline?data=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+xxx+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/////xx==`
Any idea on what I should do?

**Comment by dim13** [comment]
This looks like a valid standard base64 encoding. Which error do you get?
