### ISSUE TITLE
Makefile or build instructions?

### ISSUE THREAD

**Issue by odinho** [dim13/otpauth#14]
I  bet many people who don't really are used to compiling go apps just want to use this to transfer. Like me.

But I don't understand how to (I will once I investigate now, but if there's a makefile or some text in README saying what to do then others don't have to : )).

```
odin@kaa:/tmp/otpauth$ go build
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go: downloading google.golang.org/protobuf v1.26.0
go: downloading github.com/google/uuid v1.2.0
go: downloading github.com/golang/protobuf v1.5.2
http.go:4:2: package embed is not in GOROOT (/usr/lib/go-1.14/src/embed)
```

Of course there's the `go get` way you listed, which is likely the best way, but not the way I tried going about this. :)

**Comment by odinho** [comment]
Meh. It was old go version, -- I though I was running a reasonably modern distro, but you clearly need the newest-newest :P

I did't actually see you published binaries though here on github, that's even easier, and I made it work now. Thanks a lot! :)

**Comment by dim13** [comment]
As stated in README, at least Go 1.16 is required (`embed` package was introduced in).
Pre-compiled binaries for most common platforms are available too: https://github.com/dim13/otpauth/releases
