### ISSUE TITLE
Google:jtim08905@gmail.com with issuer=Google, qr image file is blank

### ISSUE THREAD

**Issue by milozen** [dim13/otpauth#20]
windows version release v0.4.1

sample:
Google:jtim08905@gmail.com

otpauth.exe -link "otpauth-migration://offline?data=CkAKFDSGl3vtrjgeInrI9pV5k78CmZ1BEhpHb29nbGU6anRpbTA4OTA1QGdtYWlsLmNvbRoGR29vZ2xlIAEoATACEAEYASAA"
otpauth://totp/Google:jtim08905@gmail.com?algorithm=SHA1&digits=6&issuer=Google&period=30&secret=GSDJO67NVY4B4IT2ZD3JK6MTX4BJTHKB

It worked correctly.

============
otpauth.exe -qr -link "otpauth-migration://offline?data=CkAKFDSGl3vtrjgeInrI9pV5k78CmZ1BEhpHb29nbGU6anRpbTA4OTA1QGdtYWlsLmNvbRoGR29vZ2xlIAEoATACEAEYASAA"

It returned a blank image file.

![image](https://user-images.githubusercontent.com/50772707/150934507-aa3dffdc-02ff-4c65-904d-e60c6f1f0dc3.png)

**Comment by dim13** [comment]
Please check https://github.com/dim13/otpauth/releases/tag/v0.4.2
