### ISSUE TITLE
How to import otpauth:// into Google Authenticator

### ISSUE THREAD

**Issue by Bluscream** [dim13/otpauth#22]
I need to do the thing that otpauth does, but in reverse

**Comment by dim13** [comment]
Use `-qr` flag to generate QR codes and scan them one-by-one with Google Authenticator app.
Shortly I'll also add a `-rev` (reverse) flag to generate QR code from original `optauth-migration://` URL.

**Comment by Bluscream** [comment]
Thanks a lot!
