### ISSUE TITLE
FYI: The Windows binary is detected on Virustotal on 2/70 engines

### ISSUE THREAD

**Issue by rekire** [dim13/otpauth#27]
Just FYI: https://www.virustotal.com/gui/file/735513ba94130c49d15ea9c1444891afe89668786c3ff94067fb1aa70f292507

**Comment by dim13** [comment]
If you search for [Trojan.Malware.300983.susgen](https://github.com/search?q=Trojan.Malware.300983.susgen), you'll find that there is a lot of false-positives by MaxSecure all over the place. I can do no more, then ignore this buggy scanner.

See also https://go.dev/doc/faq#virus
