### ISSUE TITLE
command not found: otpauth

### ISSUE THREAD

**Issue by notflip** [dim13/otpauth#3]
Hi, thanks for this package
I extracted the contents to a folder, ran the command `go get github.com/dim13/otpauth` but then when I try to run the command below `otpauth` I get the error `command not found: otpauth`

I installed golang using brew, on mac.

**Comment by dim13** [comment]
Go installs compiled binaries into its own `bin` directory (usually `~/go/bin`). A convenient way to make them accessible is to add
```
export PATH=$PATH:$(go env GOPATH)/bin
```
to your `~/.profile` (or `.bashrc` or `.zshrc`) file.

See also https://golang.org/doc/gopath_code.html#GOPATH

**Comment by notflip** [comment]
Aha, perfect that solves it! Thank you.

**Comment by dim13** [comment]
I'm glad I could help you. Closing issue then.
